version: "3"
services:
  some_redis:
    container_name: some_redis
    image: redis:6.2
    volumes:
      - /data/soft/redis/conf:/usr/local/etc/redis
      - /data1/service_data/redis/data:/data
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
